### ISSUE TITLE
Selecting the repository

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#112]
## Description

How we can improve the current workflow of switching or opening the repository.

### Pass URL as router params

The local path of the local repository can be passed a route params, this will also improve the speed of switching between the repositories, as it will not able to take few milliseconds for commit those mutations.

### Commit mutations (vuex)

> We are using the current approach to switch between repositories.

Based upon the index value of the repository added, it commits a mutation and changes the workspace to specific path URL and further based upon that it loads all the data on the rest of the pages by reading the data from vuex to see which is the actively selected repository.

_If you have any other better idea, we can implement to improve this flow, please them in the comment section below_

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)

**Comment by mittalyashu** [comment]
This PR https://github.com/gitthermal/thermal/pull/176 might help to resolve this issue.

**Comment by mittalyashu** [comment]
Issue is closed by #176
