### ISSUE TITLE
Run github_releases job only on tags 

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#114]

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)

**Comment by mittalyashu** [comment]
https://github.com/gitthermal/thermal/pull/169#issuecomment-539387537
