### ISSUE TITLE
Dynamic vue routes

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#131]
## Description

Leverage the full power of Vue routes by routing based on the params. These routes will follow a similar approach to GitHub.

By using dynamic routes the speed and the performance of the Application has been increased by 10x.

## Repository routes

- [x]  Workspace route: `/repository/:projectId/workspace/:branchName`
- [x]  History route: `/repository/:projectId/commits/:branchName`
- [x]  Commit route: `/repository/:projectId/commit/:commitId`
- [x] Stats route: `/repository/:projectId/stats`
- [x] Settings route: `/repository/:projectId/settings`

## Settings routes

- [x] Profile route: `/settings/profile`
- [x] Experimental route: `/settings/experimental`
- [x] Information route: `/settings/information`

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)

**Comment by mittalyashu** [comment]
Issue is closed by #176
