### ISSUE TITLE
Git commands log page

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#174]
## Description

A Git command log page, showing the list of commands run by Thermal. The list will be stored inside a session cookie and will be destroyed on closing the application.

By showing Git command logs, we don't have to output in the console and it will help users to understand the git command and the following action it does.

| Project | Command |
| --- | --- |
| `new-awesome-project` | `git commit -m "This is a git command"` |
| `thermal` | `git checkout feature/new-sidebar` |
| `website` | `git status` |
| `new-awesome-project` | `git pull` |

| Screenshot |
| --- |
| <img width="1367" alt="Frame" src="https://user-images.githubusercontent.com/29014463/61129312-c44cd300-a4d1-11e9-978a-db9c5a9ec96e.png"> |

### Data 

1. Repository path
2. Git command
3. Timestamp

### Possible features

- Filter commands based on the repository
- Filter commands based on commands `commit`, `branch` and, more
- Status for showing if command succeed or failed

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)

**Comment by mittalyashu** [comment]
Closed by #3232
