### ISSUE TITLE
Application for Mac

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#22]
## Description

Build a native application for Mac operating system.

## Links

https://www.electron.build/multi-platform-build#macos

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
