### ISSUE TITLE
Missing repository path

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#23]
## Description

Disallow users to adding of the local repository if there is no provided path.

## Steps to reproduce

- Open the app
- Click `Add Repository`.
- Hit `enter` or click button `Add repository`.

## Screenshots

![Untitled (1)](https://user-images.githubusercontent.com/29014463/57190619-c9bdf800-6f39-11e9-839b-b3ea6f95d41c.png)

**Comment by mittalyashu** [comment]
Closed by https://github.com/gitthermal/thermal/commit/f5f1349482d20f525ab1394f396db2cf23d0fafb

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
