### ISSUE TITLE
Auto-hide drop down in menu

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#24]
## Description

Clicking on each of the tiles from the menu bar will bring all the dropdown together, and to hide those dropdown, the cursor is needed to passes through the dropdown.

The dropdown should auto-hide once the cursor is moved away from the title or dropdown.

## Screenshots

![Untitled (2)](https://user-images.githubusercontent.com/29014463/57190644-1e617300-6f3a-11e9-92b8-e7d465fa3603.png)

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
