### ISSUE TITLE
Version is undefined in the information tab

### ISSUE THREAD

**Issue by kittenking** [gitthermal/thermal#3488]
## Description

The version is **undefined** in the **information tab**

## To Reproduce

![Screenshot from 2019-07-20 20-28-24](https://user-images.githubusercontent.com/53072918/61580225-11155700-ab2d-11e9-913c-2b3a0304fd73.png)

**Comment by mittalyashu** [comment]
Thank you for the bug report @kittenking.

I am aware of that bug, but the problem is that in the development mode it is working perfectly, but it doesn't work in production.

**Comment by kittenking** [comment]
@mittalyashu But here the version works fine!

![Screenshot from 2019-07-20 21-25-36](https://user-images.githubusercontent.com/53072918/61580912-fc3cc180-ab34-11e9-9ad0-d3b92f56af5a.png)

**Comment by kittenking** [comment]
**This is Fine**

https://github.com/gitthermal/thermal/blob/0c5fca2b21aa9b5003b7eca81316b19f33c8747d/src/renderer/modal/about.vue#L10

**This one not**

https://github.com/gitthermal/thermal/blob/5ad10ff40846c5735b36d2bd5219d40829506120/src/renderer/pages/settings/information.vue#L39

**Comment by mittalyashu** [comment]
Yeah, you are right. How can I miss that? 😅

If you have noticed one thing inside the code is that `appVersion` is a computed property where I am importing, the `package.json` file and getting the version property value.

Whereas in the `information.vue`, I am trying to get the package version using the environent variable.

**Comment by mittalyashu** [comment]
Since we are facing this issue, another question arises is that why we are not able to access node.js environment variable inside Electron in production.
