### ISSUE TITLE
Repository is still in welcome screen even after deleting it

### ISSUE THREAD

**Issue by kittenking** [gitthermal/thermal#3493]
## Description

The repository is still in welcome screen even after deleting it

## To Reproduce

1. Delete the Repository in file explorer
2. Go to Welcome Screen
3. All the settings will be accessible

## Expected behavior

The Repository should be removed from the welcome screen

![Screenshot from 2019-07-21 10-08-10](https://user-images.githubusercontent.com/53072918/61587039-b8cb6d00-ab9f-11e9-8489-c8bc231d6d9a.png)

**Comment by mittalyashu** [comment]
Can you verify this issue by:

1. Open DevTools
2. Application tab
3. Take the screenshot of the repository data

**Comment by kittenking** [comment]
![Screenshot from 2019-07-21 11-11-56](https://user-images.githubusercontent.com/53072918/61587456-617dca80-aba8-11e9-9cb5-f7320a59faa8.png)

**Comment by kittenking** [comment]
![Screenshot from 2019-07-21 11-13-27](https://user-images.githubusercontent.com/53072918/61587467-9558f000-aba8-11e9-9a9f-42ad52ab7be0.png)

**Comment by mittalyashu** [comment]
So, when you click on the remove button in the settings page does it also get removed from the local cache?

**Comment by kittenking** [comment]
@mittalyashu Yeah it gets removed

**Comment by mittalyashu** [comment]
Then it should also get removed from the welcome screen too.

**Comment by kittenking** [comment]
@mittalyashu If I delete from **file explorer** still the repository is in the welcome page

**Comment by mittalyashu** [comment]
Are you referring to this issue https://github.com/gitthermal/thermal/issues/30? @kittenking

**Comment by kittenking** [comment]
@mittalyashu **Exactly the same!** 

You can close this issue as Duplicate if you want!

**Comment by mittalyashu** [comment]
Sure
