### ISSUE TITLE
Create new repository

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#35]
## Description

Allowing users to create a new folder with git initialized in it.

## Screenshots

![Untitled (3)](https://user-images.githubusercontent.com/29014463/57194099-524f8f00-6f60-11e9-8c3a-be6a8591f8b8.png)

## Related issues/PR

* https://github.com/gitthermal/thermal/pull/1

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
