### ISSUE TITLE
Free, open source license?

### ISSUE THREAD

**Issue by syn-zeta** [gitthermal/thermal#3587]
It's great to see a Git client built with Vue (and, as it looks, inspired by SourceTree). I thought this is a good opportunity to get involved and contribute and learn Electron in the process, but before jumping in, I looked at the _LICENCE_ file in the root of the repo.

To my slight surprise, it didn't look to be any standard open source license that I was familiar with, but even further, section 2.2 that limits modification seems to contradict the "free, open-source" claim in the description of the software in the README.

For reference, section 2.2 of the LICENCE:

> 2.2 Modification
> You are not allowed to modify or remix the source code of the application without the permission from Copyright holder.

and the description from the README:

>Thermal is a free, open-source, cross-platform Git GUI built by developers for developers

I realize that the source is published here on GH, but would appreciate clarification here before I _modify_ the source : ]

**Comment by KaKi87** [comment]
Well, that license means Thermal is *free of charge*, but not *free for re-use*, it's legit and it's not the only software to do so.

**Comment by KaKi87** [comment]
|            | Free of charge | Public source code | Professional use | Redistributable |
|:----------:|:--------------:|:------------------:|:----------------:|:---------------:|
| Commercial |        ✗       |          ✗         |         ✗        |        ✗        |
|  Freeware  |        ✓       |          ✗         |         ✗        |        ✗        |
|   Thermal  |        ✓       |          ✓         |         ✓        |        ✗        |
|   *“FOSS”*   |        ✓       |          ✓         |         ✓        |        ✓        |

**Comment by mittalyashu** [comment]
Hello @syn-zeta,

My apologies if the `LICENSE` was not very clear.

> You are not allowed to modify or remix the source code of the application without the permission from Copyright holder.

This limitation only implised who try to modify or remix the source code and resell or try to earn money by any means.

Hope that answer your question.

Let me know if you have any other question regarding the LICENSE.

**Comment by mittalyashu** [comment]
@KaKi87 I didn't understood the table you have created.

If you have any questions regarding the LICENSE, please don't hesitate to ask :)

**Comment by mittalyashu** [comment]
@KaKi87 According the [LICENSE](https://github.com/gitthermal/thermal/blob/master/LICENCE), you can distributed the Thermal application.

**Comment by KaKi87** [comment]
The license says that Thermal can be distributed, yes, but not re-distributed (meaning : from a fork, with non-merged modifications).

**Comment by syn-zeta** [comment]
I'm not versed in the intricacies of software licenses, so I'm not really keen on discussing the details.

@KaKi87 You listed Thermal as a separate row than FOSS in your table above, which is exactly my point that Thermal doesn't seem to be "[free](https://en.wikipedia.org/wiki/The_Free_Software_Definition#The_definition_and_the_Four_Freedoms), [open-source](https://opensource.org/osd-annotated)" as it claims to be.

@mittalyashu 
>This limitation only implised who try to modify or remix the source code and resell or try to earn money by any means, since this software is free to use for everyone.

By all means (I support the idea). From what I understand, it just does not meet the requirements of "free" and "open-source" as generally understood by users and devs.

Assuming that you wouldn't want Thermal to put-off contributors and users, I'll just suggest using a standard license, and it seems that a strong Copyleft license would be the closest thing to what you want. Keep in mind that, by definition, open-source licenses do not restrict commercial usage.

**Comment by psgganesh** [comment]
@mittalyashu : First of all such a nice work on the software; keep up the good work 👍 💯 🥇 

If you are still un-sure of what license to choose, please consider choosing a valid open source license.

**One last thing**
Simple question: Can we fork and modify  ?

**Comment by KaKi87** [comment]
> Can we fork and modify ?
According to the current LICENSE, you can fork, modify and pull request, however, you can't redistribute Thermal on your own.

**Comment by mittalyashu** [comment]
Hello @psgganesh, thank you for those kind words.

> Can we fork and modify ?

According to the clause 2.2 from [LICENSE](https://github.com/gitthermal/thermal/blob/master/LICENCE) anyone is allowed to fork the repository, modify it, and contribute back to the codebase.

According to the clause 1.2 from [LICENSE](https://github.com/gitthermal/thermal/blob/master/LICENCE), you are only allowed distribute the Thermal app in packed state.

> If you are still un-sure of what license to choose, please consider choosing a valid open source license from choosealicense.com

I did read few of the open source LICENSE, but none of them fit/align with the LICENSE I am particularly looking for.
