### ISSUE TITLE
Initialize git repo

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#36]
## Description

Allow users to add a non-git repository and then showing them a modal to initialize a git repository.

## Screencasts

https://youtu.be/sM95LvX4EjQ

## Related issues/PR

* https://github.com/gitthermal/thermal/pull/4

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
