### ISSUE TITLE
Errors when adding an already existing local repository or creating a new local repository

### ISSUE THREAD

**Issue by brotenet** [gitthermal/thermal#3606]
Tested on Linux Mint 19 (Ubuntu 18.04 based) using the .DEB and AppImage packages.

When adding an already existing local repository or creating a new local repository the app hangs as soon as the project summary screen starts to load with the following errors: (log file attached)

- breadcrumbs.ts:103 TypeError: Cannot set property 'remote' of undefined
- renderer.js:1 Uncaught (in promise) Error: Cannot find module '/opt/Thermal/resources/app.asar/dist/electron/responses/StatusSummary'

![add_local_repo_1](https://user-images.githubusercontent.com/4510965/79424136-57b6b580-7fc8-11ea-9b97-173c338fe851.png)
![add_local_repo_2](https://user-images.githubusercontent.com/4510965/79424173-67ce9500-7fc8-11ea-88c1-10fb16ac1791.png)

[add_local_repo.log](https://github.com/gitthermal/thermal/files/4485370/add_local_repo.log)

**Comment by philipphutterer** [comment]
same on Windows (Version 10.0.18363 Build 18363, x64)

**Comment by Guileas** [comment]
same on ubuntu 22.04

**Comment by brotenet** [comment]
don't know if this got fixed but I stopped using this app.
