### ISSUE TITLE
Loading skeleton blocks

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#39]
## Description

This is quite often done with SVG.

There is a Vue component called **[vue-content-loader](https://github.com/egoist/vue-content-loader)** out there that has some presets and allows you to use your own SVG.

- [ ] Workspace page
- [x] History page

## Links

- [https://github.com/egoist/vue-content-loader](https://github.com/egoist/vue-content-loader)
- [https://create-vue-content-loader.netlify.com/](https://create-vue-content-loader.netlify.com/)

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
