### ISSUE TITLE
Clone remote repository

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#40]
## Screenshots

![Untitled (5)](https://user-images.githubusercontent.com/29014463/57194267-9479d000-6f62-11e9-9e11-9d26a2b8a132.png)

## Related issues/PR

* https://github.com/gitthermal/thermal/pull/7

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
