### ISSUE TITLE
File diff of working directory

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#41]
## Description

Preview file changes by clicking on a specific file from the workspace.

## Screenshots

![Untitled (6)](https://user-images.githubusercontent.com/29014463/57194311-081bdd00-6f63-11e9-9147-42a200478147.png)

**Comment by mittalyashu** [comment]
Closed by https://github.com/gitthermal/thermal/commit/75f6422c95fdc39c0d8331bde5f8b32cf0eeb911

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
