### ISSUE TITLE
Remove Vuex from commit information

### ISSUE THREAD

**Issue by mittalyashu** [gitthermal/thermal#43]
## Description

In [`commitInformation.vue`](https://github.com/gitthermal/thermal/blob/5ad10ff40846c5735b36d2bd5219d40829506120/src/renderer/components/commit/commitInformation.vue) file,  we are committing mutations and storing data inside Vuex store and later fetching the data from the same file to print it to the DOM.

Should we keeping Vuex for `commitInformation.vue` or just use local data property.

### For example

```js
    getAuthorDetail(hash) {
    			const params = [hash, "--format=%an %n %ae %n %ad"];
    			showMixin(this.currentRepository, params).then(result => {
    				let output = result.split("\n");
    				this.$store.dispatch({
    					type: "history/updateCommitInformationAuthor",
    					author_name: output[0].trim(),
    					author_email: output[1].trim(),
    					author_date: output[2].trim()
    				});
    			});
    		}
```

**Comment by mittalyashu** [comment]
Closed by https://github.com/gitthermal/thermal/pull/130

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
