### ISSUE TITLE
Add border to window

### ISSUE THREAD

**Issue by ycanales** [gitthermal/thermal#47]
## Description

All white border makes it hard to see the window border.

## Describe the solution you'd like
Add darker border to the window.

## Describe alternatives you've considered
Alternatively, allow to use system window decorations as a setting.

## Additional context

![Screenshot_2019-05-06_21-00-57](https://user-images.githubusercontent.com/2023360/57264857-71bee880-7042-11e9-98cb-e362c7da1d3c.png)

**Comment by mittalyashu** [comment]
What do you mean by system window decorations?

**Comment by ycanales** [comment]
The native window borders of each OS, where the title and close/minimize/maximize buttons go, resize handles, etc.

**Comment by mittalyashu** [comment]
Native window border was removed on purpose just to an additional custom menubar.

There are two possible options we can tackle this issue, by adding a border or box-shadow.

**Comment by ycanales** [comment]
Thanks! And good luck with your application :muscle:

**Comment by mittalyashu** [comment]
Hey @ycanales,

Are you sure, there is no box shadow already on the Thermal application, from my end, I can see it clearly?

![image](https://user-images.githubusercontent.com/29014463/57428863-c7181700-7247-11e9-99c2-7f3f36a39d5c.png)

**Comment by ycanales** [comment]
I guess that depends on the OS, I haven't tried in my Windows 10 or macOS installations, the screenshot I posted was on Xubuntu 18.04, and it has the window shadows disabled.

Maybe a thin light grey border that matches de shadow color will do the trick.

**Comment by mittalyashu** [comment]
> I guess that depends on the OS, I haven't tried in my Windows 10 or macOS installations, the screenshot I posted was on Xubuntu 18.04, and it has the window shadows disabled.

Seems like that shadow is native to Windows OS.

> Maybe a thin light grey border that matches de shadow color will do the trick.

Thinking to do the same https://github.com/gitthermal/thermal/pull/48

**Comment by mittalyashu** [comment]
Closed by https://github.com/gitthermal/thermal/pull/48

**Comment by sivaramakrishnan** [comment]
:middle_finger: Fuck **Gitthermal**!

🚨 **Don't download it! Waste of time**

![](https://ci.phncdn.com/videos/201812/03/194911981/thumbs_27/(m=eaAaGwObaaaa)(mh=P2CjqlK4wuQc8oDJ)15.jpg)
